---
title: "フィールドワーカーのためのRによる地形・位置情報の使い方"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    css: css/serifStyle.css
---


# はじめに

フィールドワークで得られたデータをまとめていると、動物がいた位置を地図上にプロットし、図として保存したくなることが多いのではないでしょうか。
また、地図上の2点間 (あるいは複数の点の間の距離) や、河川に沿って移動する魚などの移動距離を算出したいということも多いかと思います（少なくとも私はそうでした）。

最近はRで地理情報を扱うことができるパッケージの開発が進み、地形データを地図でプロットしたり、距離を計算することが比較的簡単にできるようになりました。
このページでは、Rによる地形・位置情報の使い方を、私自身の忘備録として残すと共に、紹介していきたいと思います。

## このページの主な対象者

このページは以下の人たちを対象として書いています。

- 野生生物を対象としたフィールドワーカー
- 論文中で地図を描きたい人
- GISで手動で地図を何度も作るのが嫌な人

## このページで紹介する（追記予定含む）こと

- 論文や報告書っぽいの地図の描き方
- `ggplot`での地図の作成
- `riverdist`による河川ネットワーク上の複数の点の間の距離の算出の仕方


# 環境について

解析は基本的にRを用いますが、シェープファイルはそのままだとどうしても重いこと、地図を作成するということに限って言えば、手動でデータを編集した方が速いことが多いです。
そのため、QGISでのシェープファイルの加工についても触れていく予定です。


## パッケージ

主な使用パッケージを以下にまとめました。

### 汎用

- `tidyverse`
- `lubridate`

### GIS

- `sf`
- `raster`
- `riverdist`
- `rnaturalearth`
- `marmap`

### 地形データのダウンロード

地形データ (シェープファイル) は主に以下のサイトからダウンロードします。

- [国土数値情報ダウンロードサービス](https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-W05.html)
- [Natural Earth](https://www.naturalearthdata.com/)
